name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Load Google Services json
      env:
        DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
      run: echo $DATA | base64 -di > app/google-services.json

    - name: Load Keystore Properties
      env:
        DATA: ${{secrets.KEYSTORE_PROPERTIES}}
      run: echo $DATA | base64 -di > keystore.properties

    - name: Load keystore key
      env:
        DATA: ${{secrets.KEYSTORE_KEY}}
      run: echo $DATA | base64 -di > app/src/prod/keystore-release.jks
  
    - name: Cache Gradle wrapper
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests
      run: ./gradlew testDebug --no-daemon
