name: Publish packages to Github

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Load Google Services json
        env:
          DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish packages
        run: ./gradlew publish